"""Regression test: dither images/input.jpg and compare against images/output.bmp.

The reference output.bmp was generated by a known-good external tool using the
Waveshare 7-colour ACeP palette.  This test ensures our pipeline produces an
image with the same palette, dimensions, and a similar per-colour distribution.

We do NOT require pixel-exact agreement — different dithering implementations
produce different patterns — but we do require:
  1. Exact dimensions match (800×480)
  2. Only Waveshare palette colours in the output
  3. Per-colour pixel counts within 15 % of total pixels of the reference
"""

from __future__ import annotations

import io
import pathlib

import numpy as np
import pytest
from PIL import Image

from sendspin_image_server.dither import E6_PALETTE_RGB, dither_to_pil
from sendspin_image_server.stream import _resize_for_channel

_IMAGES = pathlib.Path(__file__).parent.parent / "images"
INPUT_JPG = _IMAGES / "input.jpg"
OUTPUT_BMP = _IMAGES / "output.bmp"

DISPLAY_W, DISPLAY_H = 800, 480
TOLERANCE = 0.20   # per-colour count may differ by up to 20 % of total pixels


@pytest.fixture(scope="module")
def reference() -> np.ndarray:
    return np.array(Image.open(OUTPUT_BMP).convert("RGB"))


@pytest.fixture(scope="module")
def dithered() -> np.ndarray:
    if not INPUT_JPG.exists():
        pytest.skip(f"Input image not found: {INPUT_JPG}")
    raw = INPUT_JPG.read_bytes()
    resized = _resize_for_channel(raw, DISPLAY_W, DISPLAY_H)
    img = dither_to_pil(resized, "floyd-steinberg", "e6")
    return np.array(img)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestReferenceOutput:

    def test_dimensions_match(self, dithered: np.ndarray):
        h, w = dithered.shape[:2]
        assert (w, h) == (DISPLAY_W, DISPLAY_H), f"Expected 800×480, got {w}×{h}"

    def test_only_palette_colours_in_output(self, dithered: np.ndarray):
        palette_set = {tuple(int(v) for v in c) for c in E6_PALETTE_RGB}
        unique = {tuple(int(v) for v in px) for px in dithered.reshape(-1, 3)}
        rogue = unique - palette_set
        assert not rogue, f"Non-palette pixels in output: {rogue}"

    def test_reference_uses_expected_palette(self, reference: np.ndarray):
        """Sanity-check: the reference BMP should only contain Waveshare colours."""
        palette_set = {tuple(int(v) for v in c) for c in E6_PALETTE_RGB}
        unique = {tuple(int(v) for v in px) for px in reference.reshape(-1, 3)}
        rogue = unique - palette_set
        assert not rogue, f"Reference BMP contains unexpected colours: {rogue}"

    def test_colour_distribution_close_to_reference(
        self, dithered: np.ndarray, reference: np.ndarray
    ):
        """Each colour's pixel count should be within TOLERANCE of the reference."""
        total = dithered.shape[0] * dithered.shape[1]
        ref_flat = reference.reshape(-1, 3)
        our_flat = dithered.reshape(-1, 3)

        failures: list[str] = []
        for color in E6_PALETTE_RGB:
            c = tuple(int(v) for v in color)
            ref_frac = int(np.sum(np.all(ref_flat == c, axis=1))) / total
            our_frac = int(np.sum(np.all(our_flat == c, axis=1))) / total
            diff = abs(our_frac - ref_frac)
            if diff > TOLERANCE:
                failures.append(
                    f"  {c}: ref={ref_frac:.1%}  ours={our_frac:.1%}  diff={diff:.1%}"
                )

        assert not failures, (
            f"Per-colour distribution differs by >{TOLERANCE:.0%} for:\n" + "\n".join(failures)
        )

    def test_pixel_agreement_reasonable(self, dithered: np.ndarray, reference: np.ndarray):
        """At least 20 % of pixels should match the reference exactly.

        Different FS implementations produce different dithering patterns even
        with the same palette — the exact pixel layout is not reproducible across
        tools.  20 % agreement confirms we're in the right ballpark.
        """
        matching = int(np.sum(np.all(dithered == reference, axis=2)))
        total = dithered.shape[0] * dithered.shape[1]
        frac = matching / total
        assert frac >= 0.20, (
            f"Only {frac:.1%} of pixels match the reference (expected ≥20 %)"
        )
